# Generated by Django 4.1.3 on 2023-03-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neko_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='poblacion',
        ),
    ]
