# Generated by Django 4.1.2 on 2022-11-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neko_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='country',
            field=models.CharField(default='Philippines', max_length=255),
            preserve_default=False,
        ),
    ]
