# Generated by Django 4.1.2 on 2022-11-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neko_account', '0002_accountuser_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountuser',
            table='account_users',
        ),
    ]
