# Generated by Django 4.1.2 on 2022-11-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('purok', models.CharField(blank=True, max_length=255, null=True)),
                ('poblacion', models.CharField(blank=True, max_length=255, null=True)),
                ('barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
    ]
