# Generated by Django 4.1.2 on 2022-11-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
    ]
