# Generated by Django 4.1.3 on 2023-03-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='poblacion',
        ),
        migrations.AddField(
            model_name='ticket',
            name='publish_status',
            field=models.CharField(blank=True, default='draft', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
