# Generated by Django 4.1.2 on 2022-11-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
