# Generated by Django 4.1.2 on 2022-11-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_attachment_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
